- id: check-binary-files
  name: Check for Binary Files
  description: Checks for binary files in commits
  entry: check-binary-files
  language: python
  files: .*
- id: dos2unix
  name: dos2unix
  description: Converted DOS newlines to Unix newlines in files
  entry: dos2unix
  language: python
  files: .*
- id: terraform_fmt
  name: terraform fmt
  description: Format Terraform files using terraform fmt
  entry: terraform_fmt
  language: python
  files: \.tf$
- id: terraform_validate
  name: terraform validate
  description: Validate Terraform files using terraform validate
  entry: terraform_validate
  language: python
  files: \.tf$
