- id: check-binary-files
  name: Check for Binary Files
  description: Checks for binary files in commits
  entry: check-binary-files
  language: python
  files: .*
- id: dos2unix
  name: dos2unix
  description: Converted DOS newlines to Unix newlines in files
  entry: dos2unix
  language: python
  files: .*
